### ISSUE TITLE
Integrate Ansible Services (Docker, Nginx, Kubernetes) into Web App

### ISSUE THREAD

**Issue by MiladSadeghi** [devopshobbies/devops-gpt#121]
The integration of new backend APIs for managing Ansible services (Docker, Nginx, Kubernetes) has been completed in the web application.

- [x] Updated the frontend to interact with the new APIs for Ansible services.
- [x] Tested integration for all services (Docker, Nginx, Kubernetes) to ensure correct functionality.
- [x] Verified that the download functionality for each Ansible service is working as expected.

All features related to Ansible services (including Docker, Nginx, and Kubernetes) have been tested and verified to work correctly using the new APIs.

**Comment by mohammadll** [comment]
@MiladSadeghi Thank you for the updates. After reviewing your changes, I found that they fully meet our requirements. I will proceed with merging them now. Thank you once again for your excellent work!
